"""Generate a human-genome-shaped PGEN corpus for the SVAR2 conversion bench.

    vcfixture bulk --profile germline-1kgp-varskew.json ... -o corpus.bcf
    plink2 --bcf corpus.bcf --make-pgen --output-chr chrM --out corpus

Distinct from `scale_corpus.py`, which hand-writes VCF text for the VCF arm.
This one streams from a profile fitted on real 1kGP data (3,202 samples,
73.6M variants), which is what "human-genome-like" requires: a real site
frequency spectrum, gap distribution, variant-class mix, ti/tv, and indel
length distribution.

The two corpora come from different generators, so the VCF and PGEN RAM laws
are NOT comparable coefficient-by-coefficient. Each is fitted on, and used
for, its own backend.

Gotchas, all measured rather than assumed:

- plink2 strips the `chr` prefix from .pvar DATA rows while copying
  `##contig=<ID=chr1>` header lines verbatim, producing an internally
  inconsistent .pvar. `from_pgen` reads the data rows, so the store's
  contigs would silently become `1..22`. `--output-chr chrM` prevents it.
- The germline profile emits symbolic ALTs (`<DEL>`) at a low rate and
  plink2 passes them straight through into the .pvar. Convert with
  `skip_out_of_scope=True`.
- germline-1kgp has multiallelic_rate 0.0, so this corpus does NOT exercise
  the multiallelic allele_idx_offsets path. The fitted law should not be
  claimed to cover multiallelic-heavy cohorts.
- The `vcfixture` bulk CLI is a separate Rust binary, NOT the PyPI
  `vcfixture` package pinned in pixi.toml (which ships no console script).
  Its absence must SKIP a test, not fail it -- see `resolve_vcfixture`.
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
import subprocess
from pathlib import Path

from scripts.bench_svar2.records import CorpusManifest

# Re-exported so existing callers (sweep_pgen.sbatch, tests) keep importing
# `resolve_vcfixture` and `PROFILE` from here.
from scripts.bench_svar2.vcfixture_cli import (  # noqa: F401
    PROFILE,
    bulk,
    cli_version,
    resolve_vcfixture,
)

# Bumped whenever a change to THIS MODULE's generation logic (not the
# profile's content -- that's covered by the profile-content hash folded
# into the cache key below) would alter the generated bytes, so a stale
# cached corpus is regenerated instead of silently reused.
GENERATOR_VERSION = 1


@dataclasses.dataclass(frozen=True)
class PgenCorpusSpec:
    samples: int
    variants: int
    contigs: tuple[str, ...]
    seed: int


def corpus_stem(spec: PgenCorpusSpec) -> str:
    """Filename stem for a corpus of this shape.

    Corpora land FLAT in one directory because `model._load_manifests` globs
    `*.manifest.json` non-recursively and keys by FILENAME -- a per-corpus
    subdirectory would make every manifest `corpus.manifest.json` and they
    would collide. The shape is encoded here so `plans/build_plans.py` can
    name the corpus it wants without consulting a manifest first.
    """
    return f"pgen_s{spec.samples}_v{spec.variants}"


def generate(spec: PgenCorpusSpec, outdir: Path) -> CorpusManifest:
    """Generate (or reuse) a PGEN corpus in `outdir`.

    Cached on the full spec plus GENERATOR_VERSION plus the PROFILE file's
    own content hash: `vcfixture --seed` produces byte-identical output
    regardless of thread count, so a corpus is reproducible and there is no
    reason to pay for it twice. The profile-content hash means editing
    `germline-1kgp-varskew.json` invalidates cached corpora on its own,
    without requiring a manual GENERATOR_VERSION bump.
    """
    outdir.mkdir(parents=True, exist_ok=True)
    stem = corpus_stem(spec)
    manifest_path = outdir / f"{stem}.manifest.json"
    profile_hash = hashlib.sha256(PROFILE.read_bytes()).hexdigest()
    # Round-tripped through JSON before comparing: `dataclasses.asdict(spec)`
    # holds `contigs` as a tuple, but the cached copy loaded back off disk
    # holds it as a list (JSON has no tuple type). Comparing the raw dict
    # against the loaded one would never match, and the corpus would be
    # silently regenerated on every call.
    key = json.loads(
        json.dumps(
            {
                **dataclasses.asdict(spec),
                "generator_version": GENERATOR_VERSION,
                "profile_hash": profile_hash,
            }
        )
    )

    if manifest_path.exists():
        cached = json.loads(manifest_path.read_text())
        if cached.get("_key") == key and Path(cached["path"]).exists():
            payload = {k: v for k, v in cached.items() if k != "_key"}
            payload["contigs"] = tuple(payload["contigs"])
            payload["format_fields"] = tuple(payload["format_fields"])
            return CorpusManifest(**payload)

    bcf = outdir / f"{stem}.bcf"
    bulk(
        samples=spec.samples,
        variants=spec.variants,
        contigs=spec.contigs,
        seed=spec.seed,
        fmt="bcf",
        out=bcf,
    )

    # --output-chr chrM: keep the `chr` prefix on .pvar DATA rows. Without it
    # plink2 writes `1` in the body while copying `##contig=<ID=chr1>` into
    # the header, and from_pgen (which reads the body) yields a store whose
    # contigs silently disagree with the source BCF's.
    subprocess.run(
        [
            "plink2",
            "--bcf",
            str(bcf),
            "--make-pgen",
            "--output-chr",
            "chrM",
            "--out",
            str(outdir / stem),
        ],
        check=True,
    )

    pgen = outdir / f"{stem}.pgen"
    manifest = CorpusManifest(
        path=str(pgen),
        samples=spec.samples,
        variants=spec.variants,
        contigs=spec.contigs,
        format_fields=(),
        ploidy=2,
        cells=spec.samples * spec.variants,
        compressed_bytes=pgen.stat().st_size,
        seed=spec.seed,
        generator_version=GENERATOR_VERSION,
    )
    payload = dataclasses.asdict(manifest)
    payload["_key"] = key
    manifest_path.write_text(json.dumps(payload, indent=1) + "\n")
    return manifest
