"""Generate a human-genome-shaped PGEN corpus for the SVAR2 conversion bench.

    vcfixture bulk --profile germline-1kgp-varskew.json ... -o corpus.bcf
    plink2 --bcf corpus.bcf --make-pgen --output-chr chrM --out corpus

Distinct from `scale_corpus.py`, which hand-writes VCF text for the VCF arm.
This one streams from a profile fitted on real 1kGP data (3,202 samples,
73.6M variants), which is what "human-genome-like" requires: a real site
frequency spectrum, gap distribution, variant-class mix, ti/tv, and indel
length distribution.

The two corpora come from different generators, so the VCF and PGEN RAM laws
are NOT comparable coefficient-by-coefficient. Each is fitted on, and used
for, its own backend.

Gotchas, all measured rather than assumed:

- plink2 strips the `chr` prefix from .pvar DATA rows while copying
  `##contig=<ID=chr1>` header lines verbatim, producing an internally
  inconsistent .pvar. `from_pgen` reads the data rows, so the store's
  contigs would silently become `1..22`. `--output-chr chrM` prevents it.
- The germline profile emits symbolic ALTs (`<DEL>`) at a low rate and
  plink2 passes them straight through into the .pvar. Convert with
  `skip_out_of_scope=True`.
- germline-1kgp has multiallelic_rate 0.0, so this corpus does NOT exercise
  the multiallelic allele_idx_offsets path. The fitted law should not be
  claimed to cover multiallelic-heavy cohorts.
"""

from __future__ import annotations

import dataclasses
import json
import os
import shutil
import subprocess
from pathlib import Path

from scripts.bench_svar2.records import CorpusManifest

PROFILE = Path(__file__).parent / "profiles" / "germline-1kgp-varskew.json"

# Bumped whenever a change to this module would alter the generated bytes,
# so a stale cached corpus is regenerated instead of silently reused.
GENERATOR_VERSION = 1


@dataclasses.dataclass(frozen=True)
class PgenCorpusSpec:
    samples: int
    variants: int
    contigs: tuple[str, ...]
    seed: int


def resolve_vcfixture() -> Path:
    """Locate the `vcfixture` bulk CLI.

    This is NOT the PyPI `vcfixture` package pinned in pixi.toml -- that
    ships no console script (no entry_points.txt, no bin/vcfixture). The
    bulk generator is a separate Rust binary. Shelling out to a bare
    `vcfixture` therefore passes on a dev box that happens to have it built
    and fails in CI with FileNotFoundError, so resolution is explicit and
    the error says how to fix it.
    """
    env = os.environ.get("VCFIXTURE_BIN")
    if env:
        p = Path(env)
        if p.is_file():
            return p
        raise FileNotFoundError(f"VCFIXTURE_BIN={env} is not a file")
    found = shutil.which("vcfixture")
    if found:
        return Path(found)
    raise FileNotFoundError(
        "vcfixture bulk CLI not found. It is a Rust binary, separate from the "
        "PyPI `vcfixture` package (which has no CLI). Install it with "
        "`cargo install vcfixture --features cli`, or point VCFIXTURE_BIN at "
        "an existing build."
    )


def apportion(total: int, weights: dict[str, float]) -> dict[str, int]:
    """Split `total` across keys proportional to `weights`, summing exactly.

    Largest-remainder, with a floor of 1 per key: a contig declared in the
    header but carrying zero records is the exact shape that crashed
    from_vcf_list in issue #122, and it is not a case this bench wants to
    spend a corpus on.
    """
    if total < len(weights):
        raise ValueError(
            f"cannot give {len(weights)} contigs at least one record each "
            f"out of {total}"
        )
    total_w = sum(weights.values())
    exact = {k: total * w / total_w for k, w in weights.items()}
    counts = {k: max(1, int(v)) for k, v in exact.items()}
    # Distribute the remainder by descending fractional part, breaking ties
    # on key so the result never depends on dict iteration order.
    short = total - sum(counts.values())
    order = sorted(weights, key=lambda k: (-(exact[k] - int(exact[k])), k))
    i = 0
    while short > 0:
        counts[order[i % len(order)]] += 1
        short -= 1
        i += 1
    while short < 0:
        k = order[i % len(order)]
        if counts[k] > 1:
            counts[k] -= 1
            short += 1
        i += 1
    return counts


def _weights_for(contigs: tuple[str, ...]) -> dict[str, float]:
    """Per-contig split weights from the derived profile.

    The derived profile already carries n_variants in `density_per_kb`
    (see profiles/derive_varskew.py), so this reads the field vcfixture
    itself would use.
    """
    profile = json.loads(PROFILE.read_text())
    by_id = {}
    for c in profile["fitted"]["contigs"]:
        by_id[c["id"]] = float(c["density_per_kb"])
        by_id[f"chr{c['id']}"] = float(c["density_per_kb"])
    missing = [c for c in contigs if c not in by_id]
    if missing:
        raise ValueError(f"profile has no fitted entry for: {', '.join(missing)}")
    return {c: by_id[c] for c in contigs}


def corpus_stem(spec: PgenCorpusSpec) -> str:
    """Filename stem for a corpus of this shape.

    Corpora land FLAT in one directory because `model._load_manifests` globs
    `*.manifest.json` non-recursively and keys by FILENAME -- a per-corpus
    subdirectory would make every manifest `corpus.manifest.json` and they
    would collide. The shape is encoded here so `plans/build_plans.py` can
    name the corpus it wants without consulting a manifest first.
    """
    return f"pgen_s{spec.samples}_v{spec.variants}"


def generate(spec: PgenCorpusSpec, outdir: Path) -> CorpusManifest:
    """Generate (or reuse) a PGEN corpus in `outdir`.

    Cached on the full spec plus GENERATOR_VERSION: `vcfixture --seed`
    produces byte-identical output regardless of thread count, so a corpus
    is reproducible and there is no reason to pay for it twice.
    """
    outdir.mkdir(parents=True, exist_ok=True)
    stem = corpus_stem(spec)
    manifest_path = outdir / f"{stem}.manifest.json"
    # Round-tripped through JSON before comparing: `dataclasses.asdict(spec)`
    # holds `contigs` as a tuple, but the cached copy loaded back off disk
    # holds it as a list (JSON has no tuple type). Comparing the raw dict
    # against the loaded one would never match, and the corpus would be
    # silently regenerated on every call.
    key = json.loads(
        json.dumps({**dataclasses.asdict(spec), "generator_version": GENERATOR_VERSION})
    )

    if manifest_path.exists():
        cached = json.loads(manifest_path.read_text())
        if cached.get("_key") == key and Path(cached["path"]).exists():
            payload = {k: v for k, v in cached.items() if k != "_key"}
            payload["contigs"] = tuple(payload["contigs"])
            payload["format_fields"] = tuple(payload["format_fields"])
            return CorpusManifest(**payload)

    vcfixture = resolve_vcfixture()
    bcf = outdir / f"{stem}.bcf"
    subprocess.run(
        [
            str(vcfixture),
            "bulk",
            "--profile",
            str(PROFILE),
            "--samples",
            str(spec.samples),
            "--contigs",
            ",".join(spec.contigs),
            "--records",
            str(spec.variants),
            "--payload",
            "gt-only",
            "--format",
            "bcf",
            "--seed",
            str(spec.seed),
            "-o",
            str(bcf),
        ],
        check=True,
    )

    # --output-chr chrM: keep the `chr` prefix on .pvar DATA rows. Without it
    # plink2 writes `1` in the body while copying `##contig=<ID=chr1>` into
    # the header, and from_pgen (which reads the body) yields a store whose
    # contigs silently disagree with the source BCF's.
    subprocess.run(
        [
            "plink2",
            "--bcf",
            str(bcf),
            "--make-pgen",
            "--output-chr",
            "chrM",
            "--out",
            str(outdir / stem),
        ],
        check=True,
    )

    pgen = outdir / f"{stem}.pgen"
    manifest = CorpusManifest(
        path=str(pgen),
        samples=spec.samples,
        variants=spec.variants,
        contigs=spec.contigs,
        format_fields=(),
        ploidy=2,
        cells=spec.samples * spec.variants,
        compressed_bytes=pgen.stat().st_size,
        seed=spec.seed,
        generator_version=GENERATOR_VERSION,
    )
    payload = dataclasses.asdict(manifest)
    payload["_key"] = key
    manifest_path.write_text(json.dumps(payload, indent=1) + "\n")
    return manifest
