"""Shared record schema for the SVAR2 scale-bench harness.

Every other module in this package reads or writes these types. They are frozen
so a record cannot be mutated after a run is recorded, and the JSON codec
restores tuples explicitly because JSON has no tuple type -- without that,
round-tripped records compare unequal and resumption silently re-runs points.
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
import typing
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal, TypeVar

T = TypeVar("T")


@dataclass(frozen=True)
class CorpusManifest:
    """Shape of one generated corpus. Written next to the .vcf.gz.

    Consumers read shape from here rather than parsing filenames, so a corpus
    can be renamed or relocated without breaking a sweep.
    """

    path: str
    samples: int
    variants: int
    contigs: tuple[str, ...]
    format_fields: tuple[str, ...]
    ploidy: int
    cells: int
    compressed_bytes: int
    seed: int
    generator_version: int
    # The `vcfixture bulk` CLI version this corpus came from, for corpora that
    # used it (empty for `scale_corpus.py`'s own generator). Separate from
    # `generator_version`, which versions THIS harness's generation logic:
    # v0.5.0 of the CLI changed generated bytes for a given seed, so the two
    # move independently and pooling across either is wrong.
    generator_cli_version: str = ""

    @property
    def chunk_bytes(self) -> int:
        """Analytic bytes of one dense chunk at `chunk_size` variants.

        Mirrors `_auto_chunk_size`'s cost model: packed presence grid plus
        staged FORMAT values. Callers multiply by chunk_size.
        """
        grid = (self.samples * self.ploidy) // 8
        fmt = len(self.format_fields) * self.samples * 4
        return grid + fmt


@dataclass(frozen=True)
class SweepPoint:
    """One configuration to measure. `point_id` is content-derived so a
    resumed sweep can skip points it already recorded."""

    corpus: str
    reader_workers: int
    concurrent_chroms: int | None
    shard_htslib: int
    overshard: int
    chunk_size: int
    threads: int
    reps: int
    rss_ceiling_mb: int | None = None
    # Which conversion path this point measures. Defaults to "vcf" so every
    # call site that builds a `SweepPoint` without naming a backend keeps
    # working unchanged (all pre-Task-8 construction sites use only the VCF
    # path). NOTE: `point_id` hashes with `sort_keys=True`, so a SHA256 over
    # the sorted JSON payload has no positional stability -- adding this
    # field changes `point_id` for every point, existing or new, regardless
    # of where in the dataclass it is declared or what its default is. There
    # is no field placement that preserves ids across this change; "added
    # last" only keeps existing constructor calls source-compatible.
    backend: Literal["vcf", "pgen"] = "vcf"

    @property
    def point_id(self) -> str:
        payload = json.dumps(dataclasses.asdict(self), sort_keys=True)
        return hashlib.sha256(payload.encode()).hexdigest()[:16]


@dataclass(frozen=True)
class ProbeRecord:
    """Result of one instrumented conversion run.

    `ok=False` with `oom_at_rss_mb` set is a legitimate datum, not an error --
    demonstrating that the current chunk_size OOMs at scale is a deliverable.
    """

    point_id: str
    ok: bool
    wall_s: float
    phase1_s: float
    cpu_s: float
    maxrss_mb: float
    digest: str
    dense_cap: int
    dense_occupancy: tuple[int, ...]
    cpu_shard_pct: tuple[float, ...]
    cpu_exec_pct: tuple[float, ...]
    pending_highwater: int
    pending_bytes_highwater: int
    shard_unit_secs: tuple[float, ...]
    oom_at_rss_mb: float | None = None
    error: str | None = None
    # Machine this point was measured on. NOT part of `point_id`, deliberately
    # -- resuming a preempted sweep on a different node must still skip points
    # already paid for. But that is exactly why it has to be RECORDED: two
    # records can share a point_id and disagree wildly. Measured, the same
    # point (holdout_f0, w=1, chunk 875, point_id 2ac9bbbfbe0dc691) took
    # 151.9s on one node and 73.2s on another -- a 2.08x spread that the
    # hold-out gate charged to the model as a 40% "MODEL FAILURE" when the
    # true error against same-node data was 3.3%. Without this field a
    # cross-node comparison is invisible.
    #
    # Defaulted to "" so records written before this field existed still load
    # (`from_json` drops unknown keys but cannot invent missing ones).
    node: str = ""
    # The concurrency the planner ACTUALLY dispatched, parsed from the child's
    # `pipeline config` line. `SweepPoint.concurrent_chroms` is only the
    # REQUEST and is None whenever the point let the planner choose, which
    # made every such point unfittable -- 12 of the 58 rows in the 2026-08-08
    # PGEN crossed sweep (issue #158). None still means UNOBSERVED, never 1.
    #
    # Defaulted for the same reason `node` is: records written before this
    # field existed must still load.
    concurrent_chroms_used: int | None = None


@dataclass(frozen=True)
class VLaw:
    """phase1_s ~ intercept + slope * variants."""

    slope_s_per_variant: float
    intercept_s: float
    r2: float
    n_points: int
    max_extrapolation_factor: float


@dataclass(frozen=True)
class CostLaw:
    """cost(S) = alpha * S**beta, fitted on logs."""

    name: str
    alpha: float
    beta: float
    beta_ci95: tuple[float, float]
    n_points: int


@dataclass(frozen=True)
class RamLaw:
    """peak_rss_mb ~ base_mb + per_sample_mb * samples
    + cc * (per_contig_mb + kappa * (workers + pending_hw) * chunk_MB)

    Mirrors `src/budget.rs`'s `RamLaw` exactly, including `plan_sharded`'s
    multiplication by `cc`. It did NOT always: the fit was cc-blind while the
    consumer multiplied by `concurrent_chroms`, so the fitted `kappa` was not
    the quantity production used and the resulting "safety margin" was a
    double-count artifact rather than a chosen factor (issue #158).

    `per_sample_mb` is NOT optional bookkeeping: peak RSS carries a large
    cohort-sized term that has nothing to do with chunk bytes. Holding
    chunk_bytes pinned at 10.9 MB and varying only the cohort, measured RSS
    runs 789 MB (S=4,000) -> 5,061 MB (S=500,000) -- a 6.4x spread the
    chunk term cannot express. Modelling that as a bare constant left the
    fit at R^2=0.057 and dragged `kappa` to 2.94 against a per-worker slope
    implying ~13, which in turn is what the H3 verdict is computed from.

    `per_contig_mb` prices what one live contig pipeline holds independently
    of `chunk_bytes`. It is 0.0 for a backend whose sweep never varied
    `concurrent_chroms` at fixed (S, chunk_size), because such a sweep carries
    no information about it.

    `worst_ratio` is the gate: the largest predicted/measured ratio over the
    fitted points. A law is an upper BOUND, so `worst_ratio` is the quantity
    to minimise and `r2` is only descriptive -- see `fit_ram_law`.
    """

    base_mb: float
    per_sample_mb: float
    kappa: float
    r2: float
    n_points: int
    # Declared last, after the pre-existing fields, purely so the many
    # positional `RamLaw(...)` constructions in the tests keep working. The
    # 0.0 default carries the documented meaning "not fitted for this
    # backend", which is the same thing `RamLaw::VCF` ships.
    per_contig_mb: float = 0.0
    # Per-contig cost that scales with cohort width. The 2026-08-08 PGEN
    # crossed sweep measured the per-contig slope at 83.7 MB (S=4,000), 263 MB
    # (S=32,000) and 301 MB (S=128,000) -- a bracket that grows with S, which a
    # single additive `per_contig_mb` cannot express. 0.0 means "not fitted",
    # which is the form the law had before this field existed.
    per_contig_per_sample_mb: float = 0.0
    worst_ratio: float = float("nan")
    margin: float = 1.0


@dataclass(frozen=True)
class Verdict:
    hypothesis: str  # "H1" | "H2" | "H3" | "none"
    rationale: str
    evidence: dict[str, Any] = field(default_factory=dict)


# --- codecs -----------------------------------------------------------------


def _tuple_fields(cls: type) -> dict[str, type]:
    """Field names whose annotation is a tuple type. JSON round-trips them as
    lists, so they must be re-coerced or frozen-dataclass equality fails."""
    hints = typing.get_type_hints(cls)
    out = {}
    for f in dataclasses.fields(cls):
        origin = typing.get_origin(hints[f.name])
        if origin is tuple:
            args = typing.get_args(hints[f.name])
            out[f.name] = args[0] if args else str
    return out


def to_json(obj: Any) -> str:
    return json.dumps(dataclasses.asdict(obj), sort_keys=True)


def from_json(cls: type[T], s: str) -> T:
    raw = json.loads(s)
    coerce = _tuple_fields(cls)
    for name, elem in coerce.items():
        if name in raw and raw[name] is not None:
            raw[name] = tuple(elem(v) for v in raw[name])
    known = {f.name for f in dataclasses.fields(cls)}
    return cls(**{k: v for k, v in raw.items() if k in known})


def append_ndjson(path: Path, obj: Any) -> None:
    """Append one record and fsync. A preempted Slurm job must not lose the
    point it just finished paying for."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a") as fh:
        fh.write(to_json(obj) + "\n")
        fh.flush()
        import os

        os.fsync(fh.fileno())


def read_ndjson(path: Path, cls: type[T]) -> list[T]:
    if not Path(path).exists():
        return []
    return [
        from_json(cls, line)
        for line in Path(path).read_text().splitlines()
        if line.strip()
    ]
