from pathlib import Path

import pytest

from scripts.bench_svar2.records import CorpusManifest, ProbeRecord, to_json
from scripts.bench_svar2.regression import (
    CORPUS,
    WORKERS,
    _baselines_by_point_id,
    _points,
    check,
    corpus_is_current,
    wall_deltas,
)

pytestmark = pytest.mark.bench


def _rec(pid: str, wall: float, rss: float = 100.0) -> ProbeRecord:
    return ProbeRecord(
        point_id=pid,
        ok=True,
        wall_s=wall,
        phase1_s=wall,
        cpu_s=wall,
        maxrss_mb=rss,
        digest="aaa",
        dense_cap=6,
        dense_occupancy=(0,),
        cpu_shard_pct=(100.0,),
        cpu_exec_pct=(50.0,),
        pending_highwater=0,
        pending_bytes_highwater=0,
        shard_unit_secs=(1.0,),
    )


BASE = {"p0": {"wall_s": 10.0, "maxrss_mb": 100.0}}


def test_within_tolerance_reports_nothing():
    assert check([_rec("p0", 11.0)], BASE, tolerance=0.25) == []


def test_wall_regression_alone_is_not_a_hard_failure():
    # wall_s is informational only (fix round 1, Finding 2): baselines are
    # recorded under whatever contention happens to be on the box at record
    # time, so a wall-time-only regression must not fail the gate.
    assert check([_rec("p0", 14.0)], BASE, tolerance=0.25) == []


def test_wall_delta_is_still_reported_informationally():
    msgs = wall_deltas([_rec("p0", 14.0)], BASE)
    assert any("wall_s" in m for m in msgs)


def test_rss_regression_is_reported():
    problems = check([_rec("p0", 10.0, rss=200.0)], BASE, tolerance=0.25)
    assert any("maxrss_mb" in p for p in problems)


def test_improvement_is_not_a_regression():
    assert check([_rec("p0", 4.0, rss=10.0)], BASE, tolerance=0.25) == []


def test_missing_baseline_is_reported_not_silently_passed():
    problems = check([_rec("unknown", 10.0)], BASE, tolerance=0.25)
    assert any("no baseline" in p for p in problems)


def test_failed_run_is_always_a_regression():
    bad = ProbeRecord(**{**_rec("p0", 10.0).__dict__, "ok": False, "error": "boom"})
    assert check([bad], BASE, tolerance=0.25) != []


def _manifest(tmp_path: Path, **overrides) -> Path:
    fields = {
        "path": str(tmp_path / "reg.vcf.gz"),
        "samples": CORPUS["samples"],
        "variants": CORPUS["variants"],
        "contigs": tuple(CORPUS["contigs"]),
        "format_fields": (),
        "ploidy": 2,
        "cells": 1,
        "compressed_bytes": 1,
        "seed": CORPUS["seed"],
        "generator_version": 1,
        **overrides,
    }
    path = tmp_path / "reg.manifest.json"
    path.write_text(to_json(CorpusManifest(**fields)))
    return path


def test_absent_corpus_is_not_current(tmp_path: Path):
    assert not corpus_is_current(tmp_path / "reg.manifest.json")


def test_matching_corpus_is_current(tmp_path: Path):
    assert corpus_is_current(_manifest(tmp_path))


@pytest.mark.parametrize(
    "override",
    [
        {"variants": CORPUS["variants"] * 10},
        {"samples": CORPUS["samples"] + 1},
        {"seed": CORPUS["seed"] + 1},
        {"contigs": ("chr1", "chr2")},
        {"format_fields": ("DP",)},
    ],
)
def test_stale_corpus_is_regenerated_not_silently_reused(tmp_path: Path, override):
    # The corpus is cached by filename, so shrinking CORPUS (as fix round 1
    # did, 20_000 -> 2_000 variants) leaves any existing workdir measuring the
    # OLD corpus. That matters because the hard gate is one-sided: baselines
    # recorded on the big corpus and checked against the small one are never
    # exceeded, so every point passes vacuously and the gate silently stops
    # gating. Each field that changes the generated bytes must invalidate.
    assert not corpus_is_current(_manifest(tmp_path, **override))


def test_baseline_keyed_by_workers_survives_a_workdir_change():
    # Fix round 1, Finding 1: SweepPoint.point_id hashes `corpus`, which is
    # derived from --workdir (defaulting to $CLAUDE_JOB_DIR/tmp/bench_reg).
    # CLAUDE_JOB_DIR is a per-session ephemeral path, so two sessions on the
    # exact same box/cores get DIFFERENT point_ids for the "same" point. A
    # baseline file keyed by point_id would be unusable outside the session
    # that recorded it. Simulate two different sessions (two different
    # manifest paths, same threads) and confirm a reader_workers-keyed raw
    # baseline dict maps onto both without loss.
    raw = {
        "1": {"wall_s": 10.0, "maxrss_mb": 100.0},
        "3": {"wall_s": 8.0, "maxrss_mb": 110.0},
        "7": {"wall_s": 6.0, "maxrss_mb": 120.0},
    }
    points_a = _points(Path("/job/aaaaaaaa/tmp/bench_reg/reg.manifest.json"), threads=8)
    points_b = _points(Path("/job/bbbbbbbb/tmp/bench_reg/reg.manifest.json"), threads=8)

    # The mechanism this finding is about: different session -> different
    # content hash, even though nothing about the code or hardware changed.
    ids_a = {pt.point_id for pt in points_a}
    ids_b = {pt.point_id for pt in points_b}
    assert ids_a.isdisjoint(ids_b)

    baselines_a = _baselines_by_point_id(points_a, WORKERS, raw)
    baselines_b = _baselines_by_point_id(points_b, WORKERS, raw)

    # Both sessions recover a baseline for every point despite the point_id
    # mismatch, and the underlying values are identical (re-keyed, not
    # re-derived).
    assert set(baselines_a) == ids_a
    assert set(baselines_b) == ids_b
    for pt, w in zip(points_a, WORKERS):
        assert baselines_a[pt.point_id] == raw[str(w)]
    for pt, w in zip(points_b, WORKERS):
        assert baselines_b[pt.point_id] == raw[str(w)]

    # And check() -- which only ever sees point_id-keyed baselines -- reports
    # no missing-baseline problems for either session once re-keyed.
    records_a = [
        _rec(pt.point_id, raw[str(w)]["wall_s"]) for pt, w in zip(points_a, WORKERS)
    ]
    problems = check(records_a, baselines_a, tolerance=0.25)
    assert not any("no baseline" in p for p in problems)
