import json
import shutil
from pathlib import Path

import pytest

from scripts.bench_svar2 import vcfixture_cli
from scripts.bench_svar2.vcf_corpus import VcfCorpusSpec, corpus_stem, generate

# The bulk CLI is a Rust binary, separate from the PyPI `vcfixture` package
# (which ships no console script). Its absence must SKIP, not fail, or CI
# breaks on a machine that never had it.
_HAVE_CLI = shutil.which("vcfixture") is not None or bool(
    __import__("os").environ.get("VCFIXTURE_BIN")
)
requires_cli = pytest.mark.skipif(not _HAVE_CLI, reason="vcfixture bulk CLI not found")


def test_corpus_stem_is_shape_derived():
    spec = VcfCorpusSpec(samples=4000, variants=350000, contigs=("chr1",), seed=42)
    assert corpus_stem(spec) == "vcfx_s4000_v350000"


@requires_cli
def test_cli_version_is_reported():
    v = vcfixture_cli.cli_version()
    assert v and v[0].isdigit(), f"expected a version string, got {v!r}"


@requires_cli
def test_generate_writes_indexed_bgzf_vcf_and_a_manifest(tmp_path: Path):
    spec = VcfCorpusSpec(samples=8, variants=44, contigs=("chr1", "chr2"), seed=42)
    m = generate(spec, tmp_path)

    vcf = Path(m.path)
    assert vcf.name == "vcfx_s8_v44.vcf.gz"
    assert vcf.exists() and vcf.stat().st_size > 0
    # The sharded reader needs an index; without one from_vcf cannot shard.
    assert (vcf.parent / f"{vcf.name}.tbi").exists() or (
        vcf.parent / f"{vcf.name}.csi"
    ).exists()

    assert m.samples == 8
    assert m.variants == 44
    assert m.cells == 8 * 44
    assert m.format_fields == ()
    assert m.ploidy == 2
    # v0.5.0 changed generated bytes for a given seed. A manifest that cannot
    # tell v0.4.0 corpora from v0.5.0 ones invites pooling incompatible data.
    assert m.generator_cli_version


@requires_cli
def test_generate_is_cached_on_the_cli_version(tmp_path: Path):
    spec = VcfCorpusSpec(samples=8, variants=44, contigs=("chr1",), seed=42)
    first = generate(spec, tmp_path)
    mtime = Path(first.path).stat().st_mtime_ns

    second = generate(spec, tmp_path)
    assert second == first
    assert Path(second.path).stat().st_mtime_ns == mtime, "should not regenerate"

    # Poison the recorded CLI version: the corpus must be regenerated, not reused.
    manifest_path = tmp_path / "vcfx_s8_v44.manifest.json"
    payload = json.loads(manifest_path.read_text())
    payload["_key"]["cli_version"] = "0.0.0-not-a-real-version"
    manifest_path.write_text(json.dumps(payload))

    third = generate(spec, tmp_path)
    assert Path(third.path).stat().st_mtime_ns != mtime, "should have regenerated"
